config/routes.rb
# typed: strict

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'posts#index'

  resources :posts do
    resources :comments
  end

  resources :paginate_posts, only: [:index]
end

app/models/application_record.rb
# typed: strict
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                 :integer          not null, primary key
#  content            :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Comment < ApplicationRecord
  validates_length_of :content, minimum: 3
  validates_length_of :content, maximum: 255

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# typed: strict

# == Schema Information
#
# Table name: posts
#
#  id                 :integer          not null, primary key
#  caption            :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_content_type :string
#  image_file_name    :string           not null
#  image_file_size    :integer          not null
#  image_updated_at   :datetime         not null
#
class Post < ApplicationRecord
  validates :image, presence: true
  validates :user_id, presence: true
  validates_length_of :caption, minimum: 3
  validates_length_of :caption, maximum: 255

  has_attached_file :image, styles: { medium: '640x' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\Z}

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # careful here, the symbol is :postS, the model is however Post...
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
# typed: strict

class ApplicationController < ActionController::Base
  def debug(msg)
    Rails.logger.debug ActiveSupport::LogSubscriber.new.send(:color, msg, :yellow)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      # the heck is that ?? allows the controller to respond in js ig...
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js
      end
    else
      flash.now[:alert] = "Your new comment couldn't be created! Please check the form."
      render(root_path)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(root_path) }
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/paginate_comments_controller.rb
class PaginateCommentsController < ApplicationController
  def index
    @current_page = params[:page]
    @comments = Post.page(@current_page).per(2)
  end
end

app/controllers/paginate_posts_controller.rb
class PaginatePostsController < ApplicationController
  def index
    @current_page = params[:page]
    @posts = Post.page(@current_page).per(2)
  end
end

app/controllers/posts_controller.rb
# typed: true

class PostsController < ApplicationController
  # to avoid code repetition
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def index
    @current_page = 1
    @posts = Post.page(@current_page).per(2)
  end

  def show; end

  # current_user is a Devise helper method that gives the currently logged in user
  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Your post has been created!'
      redirect_to @post
    else
      flash.now[:alert] = "Your new post couldn't be created! Please check the form."
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:success] = 'Post updated.'
      redirect_to @post
    else
      flash.now[:alert] = 'Update failed. Please check the form.'
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Your post has been deleted!'
    redirect_to root_path
  end

  # if you put private here, all below defined function are private
  private

  def authorize_user
    redirect_to root_path if current_user.id != @post.user.id
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:image, :caption)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
# typed: strict

module ApplicationHelper
  def alert_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def debug(msg)
    Rails.logger.debug ActiveSupport::LogSubscriber.new.send(:color, msg, :yellow)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
# typed: strict

module PostsHelper
  def form_image_select(post)
    if post.image.exists?
      return image_tag(post.image.url(:medium), id: 'image-preview',
                                                class: 'img-responsive image')
    end

    image_tag('placeholder.jpg', id: 'image-preview', class: 'img-responsive image')
  end
end

app/views/comments/_comment.html.erb
<%= content_tag(:div, class: 'comment', id: "comment_#{comment.id}") do %>
  <p class='user-name'><%= comment.user.user_name %>&nbsp &nbsp</p>
  <%= comment.content %>
  <% if current_user == comment.user %>
    <div style='margin: 0 0 0 auto'>
      <%= link_to post_comment_path(post, comment), method: :delete, format: :js, remote: true, data: {
        post_id: post.id, value: post.comments.count, confirm: "Are you sure?"
      }, id: "delete-#{comment.id}", class: "delete-comment" do %>
        <%= content_tag(:span, nil, class: ["glyphicon", "glyphicon-remove", "delete-comment-icon"]) %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/comments/create.js.erb
document.querySelector('#comments_<%= @post.id %>').innerHTML += "<%=j render 'comments/comment', post: @post, comment:
@comment %>";
document.querySelector('#comment_content_<%= @post.id %>').value = '';

app/views/comments/destroy.js.erb
document.querySelector('#comment_<%= @comment.id %>').innerHTML = ''

app/views/comments/index.html.erb
<% @comments.map do |comment| %>
  <%= render('comment', comment: comment, post: @post) %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1"
            aria-expanded="false"
          >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to("Photogram", root_path) %></div>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to('new Post', new_post_path) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li><%= link_to('Register', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'loadMoreComments', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: [:alert, alert_for(name)]) %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/paginate_posts/_index.html.erb
<% @posts.each do |post| %>
  <%= render('posts/post', post: post) %>
<% end %>

app/views/paginate_posts/_load_more_link.html.erb
<%= link_to 'Load more',
    paginate_posts_path(:page => @posts.current_page + 1),
    id: "load-more",
    :remote => true unless @posts.last_page? %>

app/views/paginate_posts/index.js.erb
document.querySelector('#posts').innerHTML += "<%=j render(partial: 'index') %>";
document.querySelector('#paginator').innerHTML = "<%=j render(partial: 'load_more_link') %>";
if(!document.querySelector('#load-more')) { document.querySelector('#paginator').remove() }

app/views/posts/_form.html.erb
<%= javascript_pack_tag('posts') %>
<div class='form-wrapper'>
  <div class='text-center'>
    <%= form_image_select(post) %>
  </div>
  <%= simple_form_for(post, html: { class: 'form-horizontal', multipart: true }) do |f| %>
    <div class="row col-md-12 text-center">
      <%= f.error_notification %>
    </div>
    <div class="container-fluid">
      <div class='form-group text-center'>
        <h4>Upload an image (this is required):</h4>
        <%= f.input(:image, label: false, input_html: { onChange: 'window.loadFile(event)', style: "margin: auto; padding: 15px 0"}) %>
      </div>
      <div class='form-group'>
        <%= f.input(:caption, label: false, placeholder: 'Add your caption', input_html: { style: "width: 100%" }) %>
      </div>
      <div class='form-group'>
        <%= f.button(:submit, class: 'btn-success btn-block') %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='post'>
  <div class='post-head'>
    <div class='user-name'><%= post.user.user_name %></div>
    <div class="time-ago">
      <%= time_ago_in_words post.created_at %>
    </div>
  </div>
  <div class='image'>
    <%= link_to(image_tag(post.image.url(:medium), class:'img-responsive center-block'), post_path(post)) %>
  </div>
  <div class='post-bottom'>
    <div class='caption'>
      <div class='comment'>
        <p class='user-name'><%= post.user.user_name %>&nbsp &nbsp</p>
        <%= post.caption %>
      </div>
      <% if post.comments.any? %>
        <%= content_tag(:div, id: "comments_#{post.id}") do %>
          <% post.comments.first(4).map do |comment| %>
            <%= render('comments/comment', comment: comment, post: post) %>
          <% end %>

          <% if post.comments.count > 4 %>
            <%= content_tag(:div, id: "#comments-paginator-#{post.id}") do %>
              <%= link_to "view all #{post.comments.count} comments",
                          post_comments_path(post), remote: true, class: 'more-comments', id:
                            "more_comments_#{post.id}", data: { post_id: "#{post.id}", type:
                  "html, value:" "#{post.comments.count}" } %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      <div class='row comment-like-form'>
        <div class='col-sm-1'>
          <%= content_tag(:span, nil, class: ["glyphicon", "glyphicon-heart-empty"]) %>
        </div>
        <div class='col-sm-11 comment-form'>
          <%= form_for([post, post.comments.build], format: :js, remote: true) do |f| %>
            <%= f.text_field :content, placeholder: 'Add a comment...', limit: 10, class: "comment_content",
                             id: "comment_content_#{post.id}", style: 'border: none' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <%= render('post', post: post) %>
<% end %>

app/views/posts/edit.html.erb
<%# simple_form_for is a simple form function %>
<%# posts_path is a rails function %>
<div class='row'>
  <%= render('form', post: @post) %>
  <div class='text-center edit-links'>
    <%= link_to('Cancel', post_path(@post))%>
    |
    <%= link_to("Delete", post_path(@post),
              method: :delete,
              data: { confirm: "Are you sure?" }) %>
  </div>
</div>

app/views/posts/index.html.erb
<div id='index-main' class='container'>
  <div id="posts" class='row posts-wrapper'>
    <%= render("paginate_posts/index") %>
  </div>
  <div id="paginator" class="row text-center">
    <%= render("paginate_posts/load_more_link") %>
  </div>
</div>

app/views/posts/index.js.erb
document.querySelector('#paginator').innerHTML = ""; 

document.querySelector('#posts').innerHTML += "<%=j render('posts') %>";
document.querySelector('#paginator').innerHTML = "<%=j link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more')%>";

app/views/posts/new.html.erb
<%# simple_form_for is a simple form function %>
<%# posts_path is a rails function %>
<%= render('form', post: @post) %>

app/views/posts/show.html.erb
<div class='row posts-wrapper'>
  <%= render 'post', post: @post %>
  <div class='text-center edit-links'>
    <%= link_to('Back to posts', posts_path)%>
    <% if @post.user.id == current_user.id %>
      |
      <%= link_to('Edit', edit_post_path(@post))%>
    <% end%>
  </div>
</div>